version: "2.0"
services:
  cajade:
    image: cajade_python
    depends_on:
      - postgres
    container_name: "cajade-system"
    volumes:
      - .:/experiment_results
    tty: true
    stdin_open: true
    networks:
       app_net:
         ipv4_address: 18.18.0.2
  postgres:
    image: cajade_postgres
    container_name: "cajade-postgres"
    ports:
      - "5432:5432"
    networks:
       app_net:
         ipv4_address: 18.18.0.3
networks:
  app_net:
      driver: bridge
      ipam:
          config:
              - subnet: 18.18.0.0/8
                gateway: 18.18.0.1
