CREATE TABLE player_game_stats
(
    game_date date NOT NULL,
    home_id integer NOT NULL,
    minutes numeric(5,2),
    offposs integer,
    points integer,
    fg_two_m integer,
    fg_two_a integer,
    fg_two_pct numeric(5,2),
    fg_three_m integer,
    fg_three_a integer,
    fg_three_pct numeric(5,2),
    nonheavefg_three_pct numeric(5,2),
    ftpoints integer,
    ptsassisted_two_s integer,
    ptsunassisted_two_s integer,
    ptsassisted_three_s integer,
    ptsunassisted_three_s integer,
    assisted_two_spct numeric(5,2),
    nonputbacksassisted_two_spct numeric(5,2),
    assisted_three_spct numeric(5,2),
    fg_three_apct numeric(5,2),
    shotqualityavg numeric(5,2),
    efgpct numeric(5,2),
    tspct numeric(5,2),
    ptsputbacks integer,
    fg_two_ablocked integer,
    fg_two_apctblocked numeric(5,2),
    fg_three_ablocked integer,
    fg_three_apctblocked numeric(5,2),
    usage numeric(5,2),
    player_id integer NOT NULL,

    assists integer,
    assistpoints integer,
    two_ptassists integer,
    three_ptassists integer,
    atrimassists integer,
    shortmidrangeassists integer,
    longmidrangeassists integer,
    corner_three_assists integer,
    arc_three_assists integer,

    rebounds integer,
    defrebounds integer,
    ftdefrebounds integer,
    defftreboundpct numeric(5,2),
    def_two_ptrebounds integer,
    def_two_ptreboundpct numeric(5,2),
    def_three_ptrebounds integer,
    def_three_ptreboundpct numeric(5,2),
    deffgreboundpct numeric(5,2),
    offrebounds integer,
    ftoffrebounds integer,
    offftreboundpct numeric(5,2),
    off_two_ptrebounds integer,
    off_two_ptreboundpct numeric(5,2),
    off_three_ptrebounds integer,
    off_three_ptreboundpct numeric(5,2),
    offfgreboundpct numeric(5,2),
    defatrimreboundpct numeric(5,2),
    defshortmidrangereboundpct numeric(5,2),
    deflongmidrangereboundpct numeric(5,2),
    defarc_three_reboundpct numeric(5,2),
    defcorner_three_reboundpct numeric(5,2),
    offatrimreboundpct numeric(5,2),
    offshortmidrangereboundpct numeric(5,2),
    offlongmidrangereboundpct numeric(5,2),
    offarc_three_reboundpct numeric(5,2),
    offcorner_three_reboundpct numeric(5,2),

    primary key(game_date, home_id, player_id),

    foreign key(game_date, home_id) references game(game_date, home_id),
    foreign key(player_id) references player(player_id)
);


-- insert into player_game_stats select 
-- s.game_date,s.home_id,s.minutes,s.offposs,s.points,s.fg_two_m,s.fg_two_a,s.fg_two_pct,s.fg_three_m,s.fg_three_a,s.fg_three_pct,
-- s.nonheavefg_three_pct,s.ftpoints,s.ptsassisted_two_s,s.ptsunassisted_two_s,s.ptsassisted_three_s,s.ptsunassisted_three_s,s.assisted_two_spct,
-- s.nonputbacksassisted_two_spct,s.assisted_three_spct,s.fg_three_apct,s.shotqualityavg,s.efgpct,s.tspct,s.ptsputbacks,s.fg_two_ablocked,
-- s.fg_two_apctblocked,s.fg_three_ablocked,s.fg_three_apctblocked,s.usage,s.player_id, 
-- a.assists,a.assistpoints,a.two_ptassists,a.three_ptassists,
-- a.atrimassists,a.shortmidrangeassists,a.longmidrangeassists,a.corner_three_assists,a.arc_three_assists,
-- r.rebounds,r.defrebounds,r.ftdefrebounds,r.defftreboundpct,r.def_two_ptrebounds,r.def_two_ptreboundpct,
-- r.def_three_ptrebounds,r.def_three_ptreboundpct,r.deffgreboundpct,r.offrebounds,r.ftoffrebounds,r.offftreboundpct,
-- r.off_two_ptrebounds,r.off_two_ptreboundpct,r.off_three_ptrebounds,r.off_three_ptreboundpct,r.offfgreboundpct,
-- r.defatrimreboundpct,r.defshortmidrangereboundpct,r.deflongmidrangereboundpct,r.defarc_three_reboundpct,
-- r.defcorner_three_reboundpct,r.offatrimreboundpct,r.offshortmidrangereboundpct,r.offlongmidrangereboundpct,
-- r.offarc_three_reboundpct,r.offcorner_three_reboundpct
-- from player_game_scoring s, player_game_assist a, player_game_rebound r
-- where s.player_id=a.player_id and s.player_id=r.player_id and
-- s.game_date=a.game_date and s.game_date=r.game_date and
-- s.home_id=a.home_id and s.home_id=r.home_id


CREATE TABLE team_game_stats(
    game_date date NOT NULL,
    offposs integer,
    points integer,
    fg_two_m integer,
    fg_two_a integer,
    fg_two_pct numeric(5,2),
    fg_three_m integer,
    fg_three_a integer,
    fg_three_pct numeric(5,2),
    nonheavefg_three_pct numeric(5,2),
    ftpoints integer,
    ptsassisted_two_s integer,
    ptsunassisted_two_s integer,
    ptsassisted_three_s integer,
    ptsunassisted_three_s integer,
    assisted_two_spct numeric(5,2),
    nonputbacksassisted_two_spct numeric(5,2),
    assisted_three_spct numeric(5,2),
    fg_three_apct numeric(5,2),
    shotqualityavg numeric(5,2),
    efgpct numeric(5,2),
    tspct numeric(5,2),
    ptsputbacks integer,
    fg_two_ablocked integer,
    fg_two_apctblocked numeric(5,2),
    fg_three_ablocked integer,
    fg_three_apctblocked numeric(5,2),
    home_id integer,
    team_id integer NOT NULL,

    assists integer,
    assistpoints integer,
    two_ptassists integer,
    three_ptassists integer,
    atrimassists integer,
    shortmidrangeassists integer,
    longmidrangeassists integer,
    corner_three_assists integer,
    arc_three_assists integer,

    rebounds integer,
    defrebounds integer,
    ftdefrebounds integer,
    defftreboundpct numeric(5,2),
    def_two_ptrebounds integer,
    def_two_ptreboundpct numeric(5,2),
    def_three_ptrebounds integer,
    def_three_ptreboundpct numeric(5,2),
    deffgreboundpct numeric(5,2),
    offrebounds integer,
    ftoffrebounds integer,
    offftreboundpct numeric(5,2),
    off_two_ptrebounds integer,
    off_two_ptreboundpct numeric(5,2),
    off_three_ptrebounds integer,
    off_three_ptreboundpct numeric(5,2),
    offfgreboundpct numeric(5,2),
    defatrimreboundpct numeric(5,2),
    defshortmidrangereboundpct numeric(5,2),
    deflongmidrangereboundpct numeric(5,2),
    defarc_three_reboundpct numeric(5,2),
    defcorner_three_reboundpct numeric(5,2),
    offatrimreboundpct numeric(5,2),
    offshortmidrangereboundpct numeric(5,2),
    offlongmidrangereboundpct numeric(5,2),
    offarc_three_reboundpct numeric(5,2),
    offcorner_three_reboundpct numeric(5,2), 

    primary key(game_date, home_id, team_id),

    foreign key(game_date, home_id) references game(game_date, home_id),
    foreign key(team_id) references team(team_id)
);