version: "2.0"
services:
  cajade:
    image: jayli2018/2021-sigmod-reproducibility-cajade_systems:latest
    depends_on:
      - postgres
    container_name: "cajade-main"
    volumes:
      - .:/experiment_results
    tty: true
    stdin_open: true
    networks:
       app_net:
         ipv4_address: 10.5.0.2
  cape:
    image: jayli2018/2021-sigmod-reproducibility-cajade_cape:latest
    depends_on:
      - postgres
    container_name: "cajade-cape"
    volumes:
      - .:/experiment_results
    tty: true
    stdin_open: true
    networks:
       app_net:
         ipv4_address: 10.5.0.4
  postgres:
    image: jayli2018/2021-sigmod-reproducibility-cajade_postgres:latest
    container_name: "cajade-psql"
    ports:
      - "5432:5432"
    networks:
       app_net:
         ipv4_address: 10.5.0.3
networks:
  app_net:
      driver: bridge
      ipam:
          config:
              - subnet: 10.5.0.0/16
                gateway: 10.5.0.1
